# Generated by Django 4.1.dev20220421102516 on 2022-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=60)),
                ('points', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
